### ISSUE TITLE
gogetdoc seems not to work when a go file has `import "C"`

### ISSUE THREAD

**Issue by leixure** [zmb3/gogetdoc#39] opened 2018-09-16 03:23 UTC
foo.h
```C
#ifndef __FOO_H__
#define __FOO_H__

inline void foo(void)
{
}

#endif//__FOO_H__
```
foo.go
```go

// Package foo is just any package
package foo

/*
#include "foo.h"
*/
import "C"

// Foo calls the foo function in C
func Foo() {
    C.foo()
}
```
bar.go
```go
package foo

// Bar calls Foo
func Bar() {
    Foo()
}
```
`gogetdoc` for `foo.Foo` and `foo.Bar` and see the former fails and the latter succeeds
```shell
$ gogetdoc -pos "foo.go:#125"
xxx/bar.go:5:2: undeclared name: Foo
gogetdoc: couldn't find foo.go in program
$ gogetdoc -pos "bar.go:#37"
import "xxx/foo"

func Bar()

Bar calls Foo

```
Now change bar.go to `import "C"`
```go
package foo

/*
void bar()
{
}
*/
import "C"

// Bar calls Foo
func Bar() {
    C.bar()
}
```
then run `gogetdoc` for `foo.Bar`
```shell
 $ gogetdoc -pos "bar.go:#70"
gogetdoc: couldn't find bar.go in program
```

**Comment by zmb3** [comment] 2018-09-17 19:10
Cgo is not currently supported, so closing this as a duplicate of #33  and #21.

I didn't find the performance with Cgo enabled to be acceptable, but I'm hoping with the advent of `go/packages` (see #38) we'll be able to resolve that.

**Closed by zmb3** 2018-09-17 19:10 UTC
